### ISSUE TITLE
Importer to simulate these FMUs?

### ISSUE THREAD

**Issue by chrbertsch** [clagms/synchronous-clock-fmus#1] opened 2024-05-27 18:34 UTC
Is there a freely available importer or example c-code available to simulate these FMUs?

**Comment by clagms** [comment] 2024-05-28 05:20
Yes i plan to include that as well here, just for illustration and testing of the FMUs :)

**Comment by clagms** [comment] 2024-08-16 08:01
Added now in https://github.com/clagms/synchronous-clock-fmus/commit/386081fb79af4ea0231637c382d60a3025c7c40b but still needs to be tested.

**Comment by chrbertsch** [comment] 2024-08-26 07:24
> Added now in [386081f](https://github.com/clagms/synchronous-clock-fmus/commit/386081fb79af4ea0231637c382d60a3025c7c40b) but still needs to be tested.

Thanks, @clagms ! Do you want to present this in tomorrow's FMI Design webmeeting?

**Comment by clagms** [comment] 2024-08-26 07:56
It's not yet ready unfortunately. But when it is ready, then I would be more than happy to do so 🙂

--
Claudio

________________________________

**Comment by clagms** [comment] 2024-08-26 14:45
PS - I cannot attend any of the design meetings unless they happen at days other than Tuesday after 1200. I'm teaching at that time 🙁

--
Claudio

________________________________

**Comment by chrbertsch** [comment] 2024-09-19 13:35
@masoud-najafi : can you run these FMUs?

**Comment by clagms** [comment] 2024-09-19 14:43
It’s not yet ready unfortunately. The porting from the original branch has lefts the fmus void of behavior. I still need to port that part. The older fmus from the referencefmus repo were tested by Masoud.

—
Claudio
________________________________

**Comment by clagms** [comment] 2024-09-24 06:07
Now it is ready :). @masoud-najafi  could you kindly run them resulting fmus by your tool? Let me know if you want me to build them. The sparse instructions are available in the readme.md file at the root of the repo.

@chrbertsch after I get confirmation from @masoud-najafi , I am more than happy to present the work to the rest :)

**Comment by masoud-najafi** [comment] 2024-09-24 07:05
Hi  Claudio, @clagms . Sure, where can I find them?

**Comment by clagms** [comment] 2024-09-24 07:08
You can either build them following the instructions on the readme, or download them from here: https://filesender.deic.dk/?s=download&token=f60f1766-2ff9-4fd9-a268-7dee3a55ca84

**Comment by masoud-najafi** [comment] 2024-09-24 07:12
Thanks, I got the binaries. Where can I get The FMUs with the source code?

**Comment by masoud-najafi** [comment] 2024-09-24 07:18
There are a few fixes that should be done, for example the FMUs fail to retrieve the shift decimal variable values through APIs (mandatory I think).

**Comment by masoud-najafi** [comment] 2024-09-24 07:31
@clagms: There is one thing else: Since all FMUs has direct feed-throgh, at clock instants, the FMUs create an algenraic loop. I'm not sure if the Supervisor and the Controller should have the direct-dependency. Please confirm this.

**Comment by clagms** [comment] 2024-09-24 09:17
> Thanks, I got the binaries. Where can I get The FMUs with the source code?

In the repository: https://github.com/clagms/synchronous-clock-fmus
The readme file contains the instructions.

> There are a few fixes that should be done, for example the FMUs fail to retrieve the shift decimal variable values through APIs (mandatory I think).

Fixing this at the moment. Thanks for catching it!

>  @clagms: There is one thing else: Since all FMUs has direct feed-throgh, at clock instants, the FMUs create an algenraic loop. I'm not sure if the Supervisor and the Controller should have the direct-dependency. Please confirm this.

No this should not be the case. Maybe there's something wrong in the model description xmls? There's no feedthrough in the Plant, nor the supervisor FMU. The controller has direct feedthrough when the clock is active. Is it the tool you're using that's highlighting the algebraic loop?

**Comment by clagms** [comment] 2024-09-24 09:27
The getintervalfraction function is now implemented @masoud-najafi :)

**Comment by clagms** [comment] 2024-09-24 09:28
FMUs available at: https://filesender.deic.dk/?s=download&token=32910819-8348-45fd-9772-cd8857617f3e

**Comment by masoud-najafi** [comment] 2024-09-24 09:29
#include <stdio.h>
is missing in the three source files: Controller.c  Supervisor.c and Plant.c. You need this include to let the source file compiled.

**Comment by masoud-najafi** [comment] 2024-09-24 09:34
shift decimal is still missing in binaries as awell as in the C codes. Maybe I'm missing something.

**Comment by clagms** [comment] 2024-09-24 09:37
You're right on the functions that are missing. I'm fixing those now. Sorry about that.

Regarding the stdio, I think you need to compile the whole thing, using cmake.
First make sure to install [cmake](https://cmake.org/).

To build the FMUs run
```powershell
cmake -B build .
cmake --build build
```

The FMUs will be created in `build/fmus`.

**Comment by masoud-najafi** [comment] 2024-09-24 09:39
> > Thanks, I got the binaries. Where can I get The FMUs with the source code?
> 
> In the repository: https://github.com/clagms/synchronous-clock-fmus The readme file contains the instructions.
> 
> > There are a few fixes that should be done, for example the FMUs fail to retrieve the shift decimal variable values through APIs (mandatory I think).
> 
> Fixing this at the moment. Thanks for catching it!
> 
> > @clagms: There is one thing else: Since all FMUs has direct feed-throgh, at clock instants, the FMUs create an algenraic loop. I'm not sure if the Supervisor and the Controller should have the direct-dependency. Please confirm this.
> 
> No this should not be the case. Maybe there's something wrong in the model description xmls? There's no feedthrough in the Plant, nor the supervisor FMU. The controller has direct feedthrough when the clock is active. Is it the tool you're using that's highlighting the algebraic loop?
The in the Plant the structure should be

    **< Output valueReference="1" dependencies=""  />**

**Comment by masoud-najafi** [comment] 2024-09-24 09:41
> You're right on the functions that are missing. I'm fixing those now. Sorry about that.
> 
> Regarding the stdio, I think you need to compile the whole thing, using cmake. First make sure to install [cmake](https://cmake.org/).
> 
> To build the FMUs run
> 
> ```powershell
> cmake -B build .
> cmake --build build
> ```
> 
> The FMUs will be created in `build/fmus`.

cmake raised this error message:

D:\Private_F\pyco\XC_gits\Caludio\synchronous-clock-fmus>cmake -B build .
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.22631.
FMI_PLATFORM: x86_64-windows
-- Configuring done
-- Generating done
-- Build files have been written to: D:/XC_gits/Caludio/synchronous-clock-fmus/build

D:\XC_gits\Caludio\synchronous-clock-fmus>**cmake --build build**
Microsoft (R) Build Engine version 16.8.2+25e4d540b pour .NET Framework
Copyright (C) Microsoft Corporation. Tous droits réservés.

  Checking Build System
  Building Custom Rule D:/XC_gits/Caludio/synchronous-clock-fmus/CMakeLists.txt
     Création de la bibliothèque D:/XC_gits/Caludio/synchronous-clock-fmus/build/temp/Controller/binarie
  s/x86_64-windows/Controller.lib et de l'objet D:/XC_gits/Caludio/synchronous-clock-fmus/build/temp/Con
  troller/binaries/x86_64-windows/Controller.exp
**Controller.obj : error LNK2019: symbole externe non résolu snprintf référencé dans la fonction fmi3GetFloat64 [D:\XC_gits\Caludio\synchronous-clock-fmus\build\Controller.vcxproj]
D:\XC_gits\Caludio\synchronous-clock-fmus\build\temp\Controller\binaries\x86_64-windows\Controller.dll :**
 fatal error LNK1120: 1 externes non résolus [D:\XC_gits\Caludio\synchronous-clock-fmus\build\Controller
.vcxproj]

**Comment by masoud-najafi** [comment] 2024-09-24 09:50
Also please include this in the plant and Supervisor xml files to declare no-feed-through on outputs.
     < Output valueReference="xxx" dependencies=""/ >

**Comment by clagms** [comment] 2024-09-24 10:02
Ok I think I fixed all of the above. Thank you SO much :).
New fmus: https://filesender.deic.dk/?s=download&token=8b95a494-4aa7-41f2-b03c-cd29a1e3063e
Hopefully you can rerun cmake and get them as well?

**Comment by masoud-najafi** [comment] 2024-09-24 12:40
Hi @clagms 
The following changes were necessary in Supervisor.c to make the whole system work. Please check them and let me know, if there are fine for you.
Thanks
Masoud

 fmi3Status fmi3ExitInitializationMode(fmi3Instance instance) {
    SupervisorInstance* comp = (SupervisorInstance*)instance;
      comp->data.pz = comp->data.z;
        return fmi3OK;
 }

fmi3Status fmi3GetEventIndicators(fmi3Instance instance,
        if (nEventIndicators == 0) return status;
**       //comp->data.pz = comp->data.z;**
        comp->data.z = 2.0 - comp->data.x;


fmi3GetFloat64(fmi3Instance instance,
                                snprintf(msg_buff, MAX_MSG_SIZE, "Value of clock s being observed outside of event mode.");
                                comp->logMessage(comp->componentEnvironment, status, "Warning", msg_buff);
                                s = fmi3Warning;
**                              // values[i] = comp->data.as_previous;
                               values[i] = comp->data.as;**
                        }



fmi3Status fmi3UpdateDiscreteStates(fmi3Instance instance,
        if (comp->data.s == true) {
                comp->data.as_previous = comp->data.as;
                comp->data.as = comp->data.as_previous * -1.0;
                comp->data.s = false;
        }
**       comp->data.pz = comp->data.z;**

**Comment by clagms** [comment] 2024-09-24 13:25
Thanks @masoud-najafi . Yeah this works fine, and the changes have been committed.
Did you get a result similar to the one below?
![](https://raw.githubusercontent.com/clagms/synchronous-clock-fmus/refs/heads/main/synchronous_control_me_ref.svg)

**Comment by masoud-najafi** [comment] 2024-09-24 14:47
With a fixed step solver I get this which is very similar to yours:
![image](https://github.com/user-attachments/assets/67677412-e9e3-492d-b199-7ff82d3235f6)

But In order to make the supervisor model more robust to work with vrriable step solvers, I needed to do these chnages too.

fmi3Status fmi3EnterEventMode(fmi3Instance instance) {
	SupervisorInstance* comp = (SupervisorInstance*)instance;
	int isZC = 0;
	comp->state = EventMode;
	isZC = comp->data.pz * comp->data.z < 0.0;
	isZC |= comp->data.pz != 0 && comp->data.z == 0;
	if (isZC) {
		// Clock s is ticking
		comp->data.s = true;
	}
	return fmi3OK;
}

Please share your final fmu binaries to check the whole system with YOUR Fmus. Then I think we are OK.

**Comment by masoud-najafi** [comment] 2024-09-24 14:51
I got this with a fixed step solver, H=0.001
![image](https://github.com/user-attachments/assets/a28f5c5a-035c-47e9-8de5-1fd3b4c5895c)

In order to make the supervisor model more robust to work with variable-step solvers, I made this change.
fmi3Status fmi3EnterEventMode(fmi3Instance instance) {
	SupervisorInstance* comp = (SupervisorInstance*)instance;
	int isZC = 0;
	comp->state = EventMode;
	isZC = comp->data.pz * comp->data.z < 0.0;
	isZC |= comp->data.pz != 0 && comp->data.z == 0;
	if (isZC) {
		// Clock s is ticking
		comp->data.s = true;
	}
	return fmi3OK;
}
Please share your final FMUs and let me test YOUR Fmus. Then I think we  are fine.

**Comment by clagms** [comment] 2024-09-25 03:59
Thank you very much @masoud-najafi ! The results look exactly what they should look like!

Here are the final FMUs, with the changes proposed above: https://filesender.deic.dk/?s=download&token=105bb061-918f-4d2f-83f3-0fb6f8acbb3b

@chrbertsch I think we're ready with this. I think I can join for half hour on the 8th of Oct meeting and present this. Would that be ok with you?

Thanks!

**Comment by chrbertsch** [comment] 2024-09-25 04:49
Thanks, @clagms  and @masoud-najafi ! 
I set this on the agenda for Oct 8th.

**Comment by clagms** [comment] 2024-09-25 07:42
Co-simulation is now supported :).

**Comment by masoud-najafi** [comment] 2024-09-25 17:32
> Thank you very much @masoud-najafi ! The results look exactly what they should look like!
> 
> Here are the final FMUs, with the changes proposed above: https://filesender.deic.dk/?s=download&token=105bb061-918f-4d2f-83f3-0fb6f8acbb3b
> 
> @chrbertsch I think we're ready with this. I think I can join for half hour on the 8th of Oct meeting and present this. Would that be ok with you?
> 
> Thanks!

Worked fine without any change.

**Comment by chrbertsch** [comment] 2024-10-08 19:48
> I set this on the agenda for Oct 8th.

Hi @clagms , perhaps you missed today's FMI Design Webmeeting or were otherwise occupied.
Could you propose one of the coming FMI Design Webmeetings to discuss this, or propose a separate date? Thanks!

**Comment by clagms** [comment] 2024-10-09 05:40
Hi Christian,

I'm very sorry for this. I was teaching and missed this. Give me a few hours to sort out my agenda and let you know which FMI design meeting I can attend, or otherwise send a doodle. Sorry for the inconvenience...

--
Claudio
________________________________

**Comment by clagms** [comment] 2024-10-09 18:58
Hi @chrbertsch ,

I can confirm I'm attending the next one (on 22 Oct), as I won't be teaching then.

I'm very sorry for having missed the last one.

Have a nice evening

**Comment by clagms** [comment] 2024-10-22 13:50
Closing this one as completed, at least the first runnable version. Thanks for the support @chrbertsch !

**Closed as completed by clagms** 2024-10-22 13:50 UTC
